apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: box-a
  template:
    metadata:
      labels:
        app: box-a
    spec:
      containers:
      - name: sensor-simulator
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          apk add --no-cache curl

          while true; do
            TEMP=$(shuf -i 20-100 -n 1)
            PRESS=$(shuf -i 900-1100 -n 1)
            M_ID="MC-$(shuf -i 1-5 -n 1)"
            TS=$(date '+%Y-%m-%d %H:%M:%S')

            JSON="{\"timestamp\":\"$TS\",\"machine_id\":\"$M_ID\",\"temperature\":$TEMP,\"pressure\":$PRESS}"

            curl -X POST http://app3-service/ingest \
                 -H "Content-Type: application/json" \
                 -d "$JSON"

            echo "Sent: $JSON"

            sleep 5
          done
