apiVersion: apps/v1
kind: Deployment
metadata:
  name: ids-app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ids-app2
  template:
    metadata:
      labels:
        app: ids-app2
    spec:
      containers:
      - name: ids-container
        image: app2:local
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: http-api
---
apiVersion: v1
kind: Service
metadata:
  name: ids-app2-service
spec:
  selector:
    app: ids-app2
  ports:
    - name: proxy-port
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
